# Site settings
title: Guía de Datos Abiertos para México
email: hola@datos.gob.mx
baseurl: "/guia-submodule-test"
url: "http://mxabierto.github.io"
twitter_username: jekyllrb
github_username:  carlosmaya

# Build settings
markdown: kramdown
gems: ['jekyll-redirect-from']